name: Capgen Unit Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      #Trigger workflow on push to any branch or branch heirarchy:
      - '**'

jobs:
  unit_tests:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.repository == 'NCAR/ccpp-framework'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: update repos and install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gfortran cmake python3 git
    - name: Run unit tests
      run: cd test && ./run_tests.sh

