name: Capgen Python Linting

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      #Trigger workflow on push to any branch or branch heirarchy:
      - '**'

jobs:
  capgen_python_linting:
    strategy:
      matrix:
        python-version: [3.7]
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.repository == 'NCAR/ccpp-framework'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pylint
    - name: Run pylint against capgen files
      run: |
        cd test && pylint
