name: Capgen Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      #Trigger workflow on push to any branch or branch heirarchy:
      - '**'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: update repos and install dependencies
      run: apt update && apt install -y cmake gcc-g++ gcc-fortran make python3 git
    - name: create python venv
      run: python3 -m venv ./ccpp-env && source ./ccpp-env/bin/activate && pip3 install -r requirements.txt
    - name: Run unit tests
      run: source ccpp-env/bin/activate && cd ccpp/test && ./run_tests.sh

